name: adventure_list
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.9.0+21

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  badges: ^3.0.2
  collection: ^1.17.1
  easy_localization: ^3.0.2

  # easy_logger is only a dependency so we can customize the logs from
  # easy_localization, just until it allows using a custom logger.
  # See: https://github.com/aissat/easy_localization/issues/374
  easy_logger: ^0.0.2

  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.2
  flutter_bloc: ^8.0.1

  # ---------------- Begin flutter_local_notifications override -------------- #
  # Override flutter_local_notifications to use the fork with the fix for
  # Flatpak until the fix is merged.
  # See: https://github.com/MaikuB/flutter_local_notifications/issues/1757
  flutter_local_notifications:
    git:
      url: https://github.com/Merrit/flutter_local_notifications.git
      ref: 310ea54cf3fafeea087a60608d6f9f4c3b6080b7
      path: flutter_local_notifications
  flutter_local_notifications_linux:
    git:
      url: https://github.com/Merrit/flutter_local_notifications.git
      ref: 03b9104dfa284eff2d43f04250ef8e3aa8c7161e
      path: flutter_local_notifications_linux
  # ----------------- End flutter_local_notifications override --------------- #

  flutter_signin_button: ^2.0.0
  flutter_slidable: ^3.0.0
  flutter_window_close: ^0.2.2
  freezed_annotation: ^2.2.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.3.1
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
      ref: 7b120b8ef8ec9f70aa1a3e0f20707aae4e9e1a05
  hive_flutter: ^1.1.0
  home_widget: ^0.2.0+1
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  launch_at_startup: ^0.2.2
  launcher_entry: ^0.1.1
  local_notifier: ^0.1.5
  logger: ^2.0.1
  # move_to_background sends the Android app to background when user exits
  # instead of the app closing entirely.
  #
  # Specifying a git fork with fixes because the PR for it hasn't been accepted.
  # https://github.com/Sayegh7/move_to_background/pull/11
  #
  # Project dead?
  move_to_background:
    git:
      url: https://github.com/ViliusP/move_to_background.git
  package_info_plus: ^4.0.0
  path_provider: ^2.0.11
  pub_semver: ^2.1.3
  rrule: ^0.2.14
  system_theme: ^2.1.0
  timezone: ^0.9.1
  tray_manager: ^0.2.0
  url_launcher: ^6.1.4
  uuid: ^3.0.6
  window_manager: ^0.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
  window_to_front: ^0.0.3
  workmanager: ^0.5.0
  xdg_desktop_portal:
    git:
      url: https://github.com/Merrit/xdg_desktop_portal.dart.git
      ref: 8d18d560ba3388627c998011a0803defc0e84c30

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: 6fb79239f99bc06fe16b95af3ec6bcc5cc1eb9e7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.4.2
  msix: ^3.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - packaging/linux/codes.merritt.adventurelist.desktop
    - translations/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/codes.merritt.adventurelist.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false

flutter_app_builder:
  app_display_name: "Adventure List"
  author: "Merritt Codes"
  identifier: codes.merritt.adventurelist
  msix_identity_name: 33694MerrittCodes.AdventureList
  msix_publisher: CN=0AA9BC0E-36DF-4B4F-BFF4-E300B746CB9D
  msix_icon_path: assets\icons\codes.merritt.adventurelist.png
  msix_capabilities: internetClient
