name: adventure_list
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.1.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.5
  firebase_auth: ^3.3.20
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^1.3.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.3
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  helpers:
    git: https://github.com/Merrit/helpers.git
  hive_flutter: ^1.1.0
  home_widget: ^0.1.6
  http: ^0.13.4
  intl: ^0.17.0
  logging: ^1.0.2
  move_to_background: ^1.0.2
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  url_launcher: ^6.1.4
  window_manager: ^0.2.5
  workmanager: ^0.5.0
  # window_to_front: ^0.0.3

dev_dependencies:
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: 4445c5b4ecdb15d37191968999489b2fcbd84e41
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/codes.merritt.adventurelist.png"

flutter_app_builder:
  app_display_name: "Adventure List"
  author: "Merritt Codes"
  identifier: codes.merritt.adventurelist
  msix_identity_name:
  msix_publisher:
  msix_icon_path:
  msix_capabilities: internetClient
