name: todo_list
description: A multiplatform Todo application that syncs

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_type:
    git:
      url: https://github.com/Merrit/device_type
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_slidable: ^0.6.0
  googleapis: ^6.0.0
  googleapis_auth: ^1.2.0
  layout: ^1.0.2
  mocktail: ^0.1.4
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
