name: adventure_list
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.14.3+29

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  badges: ^3.0.2
  collection: ^1.17.1
  easy_localization: ^3.0.2

  # easy_logger is only a dependency so we can customize the logs from
  # easy_localization, just until it allows using a custom logger.
  # See: https://github.com/aissat/easy_localization/issues/374
  easy_logger: ^0.0.2

  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.2.1
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^17.0.0
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^3.0.0
  flutter_window_close: ^1.0.0
  freezed_annotation: ^2.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  googleapis: ^13.0.0
  googleapis_auth: ^1.3.1
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
      ref: 178f12326dc3e2e18c8d3bd92ba239a1af73b600
  hive_flutter: ^1.1.0
  home_widget: ^0.6.0
  http: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.0
  launch_at_startup: ^0.3.1
  launcher_entry: ^0.1.1
  local_notifier: ^0.1.5
  logger: ^2.0.1
  package_info_plus: ^8.0.2
  path_provider: ^2.0.11
  pub_semver: ^2.1.3
  rrule: ^0.2.14
  system_theme: ^3.0.0
  timezone: ^0.9.1
  tray_manager: ^0.2.2
  url_launcher: ^6.1.4
  uuid: ^4.4.2
  window_manager: ^0.4.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
  window_to_front: ^0.0.3
  # workmanager: ^0.5.0
  # Workaround under bug is resolved:
  # https://github.com/fluttercommunity/flutter_workmanager/issues/588
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  xdg_desktop_portal:
    git:
      url: https://github.com/Merrit/xdg_desktop_portal.dart.git
      ref: 8d18d560ba3388627c998011a0803defc0e84c30

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: fe5262c6ea43b5d2fdb15fc20d84f91e63e8beff
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.4.2
  msix: ^3.6.2

flutter:
  assets:
    - assets/icons/
    - assets/fonts/
    - packaging/linux/codes.merritt.adventurelist.desktop
    - translations/
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/codes.merritt.adventurelist.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false

flutter_app_builder:
  app_display_name: "Adventure List"
  author: "Merritt Codes"
  identifier: codes.merritt.adventurelist
  languages:
    - de
    - en
    - it
    - pt-BR
  msix_identity_name: 33694MerrittCodes.AdventureList
  msix_publisher: CN=0AA9BC0E-36DF-4B4F-BFF4-E300B746CB9D
  msix_icon_path: assets\icons\codes.merritt.adventurelist.png
  msix_capabilities: internetClient
