name: adventure_list
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.3.1+15

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  badges: ^3.0.2
  collection: ^1.16.0
  desktop_integration:
    git:
      url: https://github.com/Merrit/desktop_integration.git
      ref: 78b3fc0d221bb117457f92786461b21b0f3c0777
  extension_google_sign_in_as_googleapis_auth: ^2.0.5
  firebase_auth: ^3.3.20
  firebase_core: ^1.20.0
  # Temporary lock of firebase_core_platform_interface.
  # To be removed when upgrading the firebase packages.
  firebase_core_platform_interface: 4.5.1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.2
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^1.3.0
  flutter_window_close: ^0.2.2
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.3
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
      ref: be754e0b6b23625bd83e60a2fb4f1e0939218632
  hive_flutter: ^1.1.0
  home_widget: ^0.2.0+1
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.8.0
  launcher_entry: ^0.1.1
  local_notifier: ^0.1.5
  logger: ^1.1.0
  # move_to_background sends the Android app to background when user exits
  # instead of the app closing entirely.
  #
  # Specifying a git fork with fixes because the PR for it hasn't been accepted.
  # https://github.com/Sayegh7/move_to_background/pull/11
  #
  # Project dead?
  move_to_background:
    git:
      url: https://github.com/ViliusP/move_to_background.git
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  pub_semver: ^2.1.3
  system_theme: ^2.1.0
  timezone: ^0.9.1
  tray_manager: ^0.2.0
  url_launcher: ^6.1.4
  uuid: ^3.0.6
  window_manager: ^0.3.0
  window_to_front: ^0.0.3
  workmanager: ^0.5.0

dev_dependencies:
  flutter_app_builder:
    git:
      url: https://github.com/Merrit/flutter_app_builder.git
      ref: 3c38d05af2ab6355e8c72a6d42ff7ad6c29c9348
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  mocktail: ^0.3.0
  msix: ^3.6.2
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/icons/
    - packaging/linux/codes.merritt.adventurelist.desktop

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/codes.merritt.adventurelist.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false

flutter_app_builder:
  app_display_name: "Adventure List"
  author: "Merritt Codes"
  identifier: codes.merritt.adventurelist
  msix_identity_name: codes.merritt.adventurelist
  msix_publisher: CN=0AA9BC0E-36DF-4B4F-BFF4-E300B746CB9D
  msix_icon_path: assets\icons\codes.merritt.adventurelist.png
  msix_capabilities: internetClient
