name: Build Linux
on:
  # Enable manual run
  workflow_dispatch:
  # Allow being called by other workflows
  workflow_call:
    inputs:
      pre-release:
        description: "Whether the build is for a pre-release"
        required: false
        default: false
        type: boolean

env:
  app-display-name: "Adventure List"
  author: "Merritt Codes"
  identifier: "codes.merritt.adventurelist"

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-20.04

    # ----------------------------------- Setup ------------------------------ #

    steps:
      - name: Setup Linux build requirements
        run: |
          sudo apt-get update
          # libappindicator required for tray_manager
          sudo apt-get install appindicator3-0.1 libappindicator3-dev
          # libnotify-dev required for notifications, only until the
          # following issue is resolved:
          # https://github.com/MaikuB/flutter_local_notifications/issues/746
          sudo apt-get install libnotify-dev
          # keybinder required for global hotkeys
          sudo apt-get install keybinder-3.0

      - name: Set pre-release environment variable
        if: inputs.pre-release == true
        run: echo "prerelease=true" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        # Specify the Flutter version to work around bug in new version:
        # https://github.com/flutter/flutter/issues/144873
        with:
          flutter-version: '3.19.6'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare for build
        run: |
          flutter config --enable-linux-desktop
          flutter pub get

      # ----------------------------------- Build ---------------------------- #

      - name: Generate localizations
        run: dart run easy_localization:generate --source-dir translations --output-dir lib/generated --output-file locale_keys.g.dart --format keys --skip-unnecessary-keys

      - name: Run build script
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        run: flutter pub run flutter_app_builder -v --platforms=linux

      # ---------------------------------- Upload ---------------------------- #

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: output/*
