name: Build Windows
on:
  # Enable manual run
  workflow_dispatch:
  # Allow being called by other workflows
  workflow_call:
    inputs:
      pre-release:
        description: "Whether the build is for a pre-release"
        required: false
        default: false
        type: boolean

env:
  app-display-name: "Adventure List"
  author: "Merritt Codes"
  identifier: "codes.merritt.adventurelist"
  msix-icon-path: "assets\\icons\\codes.merritt.adventurelist.png"

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    # ----------------------------------- Setup ------------------------------ #

    steps:
      - name: Set pre-release environment variable
        if: inputs.pre-release == true
        run: echo "prerelease=true" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare for build
        run: |
          # Fix error for git packages with long names
          git config --system core.longpaths true
          # Setup Flutter
          flutter config --enable-windows-desktop
          flutter pub get

      # ----------------------------------- Build ---------------------------- #

      - name: Generate localizations
        run: dart run easy_localization:generate --source-dir translations --output-dir lib/generated --output-file locale_keys.g.dart --format keys --skip-unnecessary-keys

      - name: Run build script
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        run: flutter pub run flutter_app_builder -v --platforms=windows

      # ---------------------------------- Upload ---------------------------- #

      - name: Upload Windows Store MSIX artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: windows-store-artifact
          path: output/*.msix

      # MSIX is only for publishing to the Windows Store.
      - name: Remove Windows Store artifact from release files
        run: rm output/*.msix

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: output/*
