# Create a new prerelease with every push on main

name: "pre-release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

concurrency:
  group: ci-pre-release-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-build-linux:
    uses: ./.github/workflows/build-linux.yml
  call-build-android:
    uses: ./.github/workflows/build-android.yml

  pre-release:
    name: "Pre Release"
    needs: [call-build-linux, call-build-android]
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
          # name: linux-artifacts

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: artifacts/*
