name: Run tests

on:
  # Allow being called by other workflows
  workflow_call:
  # Allow being called manually
  workflow_dispatch:

jobs:
  flutter_test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        # Specify the Flutter version to work around bug in new version:
        # https://github.com/flutter/flutter/issues/144873
        with:
          flutter-version: '3.19.6'

      - name: Setup
        run: |
          flutter pub get

      - name: Verify formatting
        run: dart format -o none --set-exit-if-changed --line-length=90 .

      - name: Run translations generation
        run: dart run easy_localization:generate --source-dir translations --output-dir lib/generated --output-file locale_keys.g.dart --format keys --skip-unnecessary-keys
      
      - name: Run code generation
        run: dart run build_runner build --delete-conflicting-outputs
        
      - name: Run tests
        run: flutter test
        
      - name: Print directory structure
        # Ensure this step runs even after a failure, but not when cancelled.
        if: success() || failure()
        run: tree -a
