name: Run tests

on:
  # Allow being called by other workflows
  workflow_call:
  # Allow being called manually
  workflow_dispatch:

jobs:
  flutter_test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0

      - name: Setup
        run: |
          flutter upgrade
          flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test
