name: Run tests

on:
  # Allow being called by other workflows
  workflow_call:
  # Allow being called manually
  workflow_dispatch:

jobs:
  flutter_test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0

      - name: Setup
        run: |
          flutter upgrade --force
          flutter pub get

      - name: Run code generation
        run: |
          dart run easy_localization:generate --source-dir translations --output-dir lib/generated --output-file locale_keys.g.dart --format keys --skip-unnecessary-keys
          dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test
